create database Case_study

use Case_study

select * from  dbo.Fact
select * from  dbo.Location
select * from  dbo.product

--Tasks to be Performed

--1. Display the number of states present in the LocationTable.

Select Count (Distinct State) as 'Number of States' from dbo.location ;


--2. How many products are of regular type?

Select count (*) as 'No of Regular Products' from dbo.product where Type ='Regular';


--3. How much spending has been done on marketing of product ID 1?

Select Sum (Marketing) as 'Total Marketing Cost of Product Id 1' from Dbo.fact where ProductId=1


--4. What is the minimum sales of a product?

select ProductId,Min(Sales) as 'Minimum Sale value'from dbo.fact Group by ProductId order by ProductId;


--5. Display the max Cost of Good Sold (COGS).

Select Max(COGS) as 'Maximum Cost of Goods Sold' from dbo.fact;

--6. Display the details of the product where product type is coffee.

select * from  dbo.product where Product_Type = 'Coffee';


--7. Display the details where total expenses are greater than 40.

Select * from Dbo.fact where Total_Expenses > 40 order by Total_expenses asc;

--8. What is the average sales in area code 719?

Select Avg(sales) as 'Average Sales of Area Code 719 ' from dbo.fact where Area_Code = 719;

--9. Find out the total profit generated by Colorado state.

Select Sum(Profit) as 'Total Profit of Colorado State'
From dbo.fact inner join Dbo.location on dbo.fact.Area_Code = dbo.location.area_code 
Where State = 'Colorado';


--10. Display the average inventory for each product ID.

Select productId,Avg(Inventory) as 'Average Inventory' from dbo.fact group by productId order by productId;

--11. Display state in a sequential order in a Location Table.

Select distinct state  from dbo.location order by state Asc;


--12.Display the average budget of the Product where the average budget margin should be greater than 100.

Select productId,Avg(budget_margin) as 'Average Budget Margin' from dbo.fact where budget_margin >=100 group by productid ;


--13. What is the total sales done on date 2010-01-01?

Select Sum(Sales) as 'Total Sales on 01-01-2010' from dbo.fact where date Like '2010-01-01';

--14. Display the average total expense of each product ID on an individual date.

select Date,ProductId ,avg (Total_expenses) as 'Average Total Expenses' from dbo.fact group by 
date,productid ;

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.

Select f.date,f.ProductId,p.product_type,p.product,f.sales,f.profit,l.state,f.Area_Code from fact f 
inner join product p on f.productid=p.productid 
inner join location l on f.Area_Code=l.Area_Code ;


--16.Display the rank without any gap to show the sales wise rank.

Select * ,Dense_rank() over (Order by sales desc) as Sales_rank from dbo.fact

--17. Find the state wise profit and sales.
 
 Select l.state,sum(f.profit) as Total_Profit,Sum(f.sales) as Total_sales from fact f inner join location l on f.Area_Code=l.area_code group by l.state


--18. Find the state wise profit and sales along with the product name.

 Select l.state,p.product,sum(f.profit) as Total_Profit,Sum(f.sales) as Total_sales from fact f inner join location l on f.Area_Code=l.area_code
 inner join product p on f.ProductId=p.productid group by p.product,l.state


--19. If there is an increase in sales of 5%, calculate the increased sales.

Select *,Sales*1.05 as Increased_sales from fact 


--20. Find the maximum profit along with the product ID and producttype.

Select Max(profit) as 'Maximum profit',f.ProductId,p.Product_Type from fact f inner join product p on f.ProductId = p.ProductId group by f.ProductId,p.Product_Type order by [Maximum profit]desc;

--21. Create a stored procedure to fetch the result according to the product type from Product Table.

CREATE PROCEDURE FetchProductByType @productType NVARCHAR(50)
AS BEGIN SELECT * FROM Product
WHERE product_type = @productType;
END;

FetchProductByType coffee


--22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.
Select *,
Case
When Total_expenses <=60 Then'Profit'
Else 'Loss'
End as 'Profit or Loss' from fact;

--23. Give the total weekly sales value with the date and product ID details. Use roll-up to pull the data in hierarchical order.

Select Datepart(week,date) as week_number ,date,productid,sum(sales) as Total_sales from fact group by rollup (Datepart(week,date),date,productid,sales);

--24. Apply union and intersection operator on the tables which consist of attribute area code.

Select Area_code from Fact union select area_code from Location ;

Select Area_code from Fact intersect select area_code from Location ;


--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.

CREATE FUNCTION PRO_TYPE(@PROD_TYP VARCHAR(20))RETURNS TABLE AS RETURN(SELECT * FROM Product WHERE Product_Type = @PROD_TYP);

SELECT * FROM dbo.PRO_TYPE('COFFEE');


--26. Change the product type from coffee to tea where product ID is 1 and undo it.

Begin transaction
Update product
set Product_Type ='Tea' where ProductId=1;

Rollback

--27. Display the date, product ID and sales where total expenses are between 100 to 200.

Select Date,ProductId,Sales from dbo.fact where Total_expenses >=100 and Total_expenses <=200;


--28. Delete the records in the Product Table for regular type.

Begin transaction
Delete from product where Type ='Regular';

rollback

select*from product

--29. Display the ASCII value of the fifth character from the column Product.

SELECT ASCII(SUBSTRING(product, 5, 1)) AS ASCII_Value
FROM Product;
